### ISSUE TITLE
Specific AppDef results in nullPointer in usercluster-controller

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/kubermatic#10840]
### What happened?

Creating a specific AppDef (see below) leads to user-controller manager crash-looping, with the following error:

```log
usercluster-controller-75998f99dc-tnn2n usercluster-controller {"level":"info","time":"2022-08-23T15:46:14.888Z","logger":"kkp-app-installation-controller","caller":"applications/installer.go:108","msg":"reconciling namespace 'prometheus-4'","applicationinstallation":"prometheus-4/prometheus-4"}
usercluster-controller-75998f99dc-tnn2n usercluster-controller {"level":"info","time":"2022-08-23T15:46:14.932Z","caller":"runtime/panic.go:838","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"kkp-app-installation-controller","object":{"name":"prometheus-4","namespace":"prometheus-4"},"namespace":"prometheus-4","name":"prometheus-4","reconcileID":"dee70c41-7f2d-46e2-91fe-caa5dfda79b0"}
usercluster-controller-75998f99dc-tnn2n usercluster-controller panic: runtime error: invalid memory address or nil pointer dereference [recovered]
usercluster-controller-75998f99dc-tnn2n usercluster-controller  panic: runtime error: invalid memory address or nil pointer dereference
usercluster-controller-75998f99dc-tnn2n usercluster-controller [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1bf70ec]
usercluster-controller-75998f99dc-tnn2n usercluster-controller
usercluster-controller-75998f99dc-tnn2n usercluster-controller goroutine 882 [running]:
usercluster-controller-75998f99dc-tnn2n usercluster-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
usercluster-controller-75998f99dc-tnn2n usercluster-controller  sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:118 +0x1f4
usercluster-controller-75998f99dc-tnn2n usercluster-controller panic({0x2c00200, 0x5d29d00})
usercluster-controller-75998f99dc-tnn2n usercluster-controller  runtime/panic.go:838 +0x207
usercluster-controller-75998f99dc-tnn2n usercluster-controller k8c.io/kubermatic/v2/pkg/applications/providers/util.HelmAuthFromCredentials({0x39effc0?, 0xc002da1e00?}, {0x3a04068?, 0xc00178e910?}, {0xc003b37920?, 0xc001cdc840?}, {0x7ffcec62d801?, 0x24?}, 0x0?)
usercluster-controller-75998f99dc-tnn2n usercluster-controller  k8c.io/kubermatic/v2/pkg/applications/providers/util/util.go:78 +0x8c
usercluster-controller-75998f99dc-tnn2n usercluster-controller k8c.io/kubermatic/v2/pkg/applications/providers/template.HelmTemplate.InstallOrUpgrade({{0x39effc0, 0xc002da1e00}, {0x7ffcec62d787, 0x25}, {0x7ffcec62d8cb, 0x13}, 0xc001feaa60, 0xc000867800, {0x7ffcec62d801, 0x12}, ...}, ...)
usercluster-controller-75998f99dc-tnn2n usercluster-controller  k8c.io/kubermatic/v2/pkg/applications/providers/template/helm.go:66 +0x210
usercluster-controller-75998f99dc-tnn2n usercluster-controller k8c.io/kubermatic/v2/pkg/applications.(*ApplicationManager).Apply(0xc0018226f0, {0x39effc0, 0xc002da1e00}, 0xc002da1e00?, {0x3a04068?, 0xc00178e910?}, {0x3a04068, 0xc001588c80}, 0xc00113b750?, {0xc003d4fe00, ...})
usercluster-controller-75998f99dc-tnn2n usercluster-controller  k8c.io/kubermatic/v2/pkg/applications/installer.go:91 +0x1be
usercluster-controller-75998f99dc-tnn2n usercluster-controller k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller.(*reconciler).handleInstallation(0xc00178f0e0, {0x39effc0, 0xc002da1e00}, 0xc001feaa60, 0xc000867800)
usercluster-controller-75998f99dc-tnn2n usercluster-controller  k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go:252 +0x68d
usercluster-controller-75998f99dc-tnn2n usercluster-controller k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller.(*reconciler).reconcile(0xc00178f0e0, {0x39effc0, 0xc002da1e00}, 0xc00207ba60?, 0xc000867800)
usercluster-controller-75998f99dc-tnn2n usercluster-controller  k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go:205 +0x691
usercluster-controller-75998f99dc-tnn2n usercluster-controller k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller.(*reconciler).Reconcile(0xc00178f0e0, {0x39effc0, 0xc002da1e00}, {{{0xc00207ba60?, 0x10?}, {0xc00207ba50?, 0x40d9e7?}}})
usercluster-controller-75998f99dc-tnn2n usercluster-controller  k8c.io/kubermatic/v2/pkg/controller/user-cluster-controller-manager/application-installation-controller/controller.go:135 +0x370
usercluster-controller-75998f99dc-tnn2n usercluster-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x39eff18?, {0x39effc0?, 0xc002da1e00?}, {{{0xc00207ba60?, 0x30ad3c0?}, {0xc00207ba50?, 0x4041f4?}}})
usercluster-controller-75998f99dc-tnn2n usercluster-controller  sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121 +0xc8
usercluster-controller-75998f99dc-tnn2n usercluster-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc001679540, {0x39eff18, 0xc0015b1dc0}, {0x2da4300?, 0xc0027b8a80?})
usercluster-controller-75998f99dc-tnn2n usercluster-controller  sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320 +0x33c
usercluster-controller-75998f99dc-tnn2n usercluster-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc001679540, {0x39eff18, 0xc0015b1dc0})
usercluster-controller-75998f99dc-tnn2n usercluster-controller  sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273 +0x1d9
usercluster-controller-75998f99dc-tnn2n usercluster-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
usercluster-controller-75998f99dc-tnn2n usercluster-controller  sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234 +0x85
usercluster-controller-75998f99dc-tnn2n usercluster-controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
usercluster-controller-75998f99dc-tnn2n usercluster-controller  sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:230 +0x325
```

### How to reproduce the issue?

1. Apply the Following AppDef to your cluster

```yaml
apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.kubermatic.k8c.io/v1","kind":"ApplicationDefinition","metadata":{"annotations":{},"name":"prometheus-4"},"spec":{"description":"Prometheus is a monitoring system and time series database.","method":"helm","versions":[{"template":{"source":{"git":{"path":"charts/prometheus","ref":{"branch":"main"},"remote":"https://gitlab.com/wurbanski/test-test-test.git"}}},"version":"1.2.3"}]}}
  creationTimestamp: "2022-08-23T14:49:55Z"
  finalizers:
  - kubermatic.k8c.io/cleanup-seed-application-definition
  generation: 3
  name: prometheus-4
  resourceVersion: "18002489"
  uid: 4812ccbb-2805-4ba9-92f9-54e7e8e079f1
spec:
  description: Prometheus is a monitoring system and time series database.
  method: helm
  versions:
  - template:
      source:
        git:
          path: charts/prometheus
          ref:
            branch: main
          remote: https://gitlab.com/wurbanski/test-test-test.git
    version: 1.2.3
```

2. Create an AppInstall that references this AppDef
3. Wait for reconciliation to throw the error

### Additional information

I already did some debugging and found the following:

it looks like it panics because it [cannot do ](https://github.com/kubermatic/kubermatic/blob/68882ca3c788ee3de1228364bbd4804b8212d7b8/pkg/applications/providers/util/util.go#L78)if source.Credentials != nil , which would happen if source itself is nil. And that seems to be the case [because util.HelmAuthFromCredentials passes Template.Source.Helm](https://github.com/kubermatic/kubermatic/blob/68882ca3c788ee3de1228364bbd4804b8212d7b8/pkg/applications/providers/template/helm.go#L66) into it. Which of course is nil since the chosen source was git

**Comment by vgramer** [comment]
for this release, we will avoid NPE, but we have to think about how to handle credentials for helm dependencies. ptal #10845
