### ISSUE TITLE
Race condition in etcd cluster initialisation when using etcd-launcher

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#10931]
### What happened?

When creating a new user cluster on KKP 2.21.0 or higher, the etcd cluster hosted in the control plane namespace can fail to fully initialise, with one of the three pods going into `CrashLoopBackOff`. The user cluster will be stuck in "Creating" due to the etcd cluster never fully initialising.

If observed carefully, the first startup of the bad pod will reveal logs like this:

<details>

```
{"level":"info","time":"2022-09-08T07:33:11.945Z","caller":"etcd-launcher/main.go:121","msg":"initializing etcd.."}
{"level":"info","time":"2022-09-08T07:33:11.945Z","caller":"etcd-launcher/main.go:122","msg":"initial-state: new"}
{"level":"info","time":"2022-09-08T07:33:11.945Z","caller":"etcd-launcher/main.go:123","msg":"initial-cluster: etcd-0=https://etcd-0.etcd.cluster-marvintest.svc.cluster.local:2381,etcd-1=https://etcd-1.etcd.cluster-marvintest.svc.cluster.local:2381,etcd-2=https://etcd-2.etcd.cluster-marvintest.svc.cluster.local:2381"}
{"level":"info","time":"2022-09-08T07:33:11.945Z","caller":"etcd-launcher/main.go:125","msg":"peer-tls-mode: strict"}
{"level":"info","time":"2022-09-08T07:33:15.649Z","caller":"etcd-launcher/main.go:144","msg":"[https://etcd-1.etcd.cluster-marvintest.svc.cluster.local:2381] is a member"}
{"level":"warn","time":"2022-09-08T07:33:15.651Z","caller":"etcd-launcher/main.go:152","msg":"No data dir, removing stale membership to rejoin cluster as new member"}
{"level":"info","time":"2022-09-08T07:33:15.673Z","caller":"etcd-launcher/main.go:267","msg":"pod is not a cluster member, trying to join.."}
{"level":"info","time":"2022-09-08T07:33:15.673Z","caller":"etcd-launcher/main.go:269","msg":"removing possibly stale data dir"}
{"level":"warn","ts":"2022-09-08T07:33:15.688Z","logger":"etcd-client","caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00016a380/etcd-0.etcd.cluster-marvintest.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: unhealthy cluster"}
{"level":"panic","time":"2022-09-08T07:33:15.688Z","caller":"etcd-launcher/main.go:162","msg":"join cluster as fresh member","error":"add itself as a member: etcdserver: unhealthy cluster"}
panic: join cluster as fresh member

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0008b6000, {0xc0004f3d00, 0x1, 0x1})
	go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc000332270, 0x4, {0x1bd1960?, 0x46?}, {0x0?, 0x0?, 0x0?}, {0xc000987ae0, 0x1, 0x1})
	go.uber.org/zap@v1.21.0/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicw(...)
	go.uber.org/zap@v1.21.0/sugar.go:204
main.main()
	k8c.io/kubermatic/v2/cmd/etcd-launcher/main.go:162 +0x10dd
```

</details>

Subsequent restarts of the pod will provide logs including the following lines:

```
{"level":"warn","ts":"2022-09-08T07:33:29.701Z","caller":"etcdserver/server.go:1150","msg":"server error","error":"the member has been permanently removed from the cluster"}
{"level":"warn","ts":"2022-09-08T07:33:29.701Z","caller":"etcdserver/server.go:1151","msg":"data-dir used by this member must be removed"}
{"level":"warn","ts":"2022-09-08T07:33:29.702Z","caller":"etcdserver/server.go:2053","msg":"stopped publish because server is stopped","local-member-id":"24b8592c6612923e","local-member-attributes":"{Name:etcd-1 ClientURLs:[https://10.44.38.188:2379 https://etcd-1.etcd.cluster-marvintest.svc.cluster.local:2379]}","publish-timeout":"7s","error":"etcdserver: server stopped"}
```

### Expected behavior

A fully initialised and running etcd cluster is set up for my new user cluster.

### How to reproduce the issue?

Create a user cluster that starts with the `etcdLauncher` feature flag (so it's either enabled globally or you create the cluster via `kubectl` from a YAML file including this feature flag). Repeat this process a couple of times until hitting the race condition.

### How is your environment configured?

- KKP version: `2.21.0` or `master`
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Other (not applicable)

### What operating system are you running in your user cluster?

Not applicable

#### Workaround

There is a workaround to fix environments affected by this bug:

Update the `Cluster` status to include the `EtcdClusterInitialized` condition under `status.conditions`:

```
EtcdClusterInitialized:
      kubermaticVersion: v2.21.0
      lastHeartbeatTime: "2022-09-08T05:33:52Z"
      message: Etcd Cluster has been initialized successfully
      status: "True"
```

Be aware that editing the status cannot be done from `kubectl edit`, you will need a plugin like [kubectl-edit-status](https://github.com/ulucinar/kubectl-edit-status) to do this. After updating the status, delete the PVC associated with the broken etcd pod and the broken etcd pod itself. A new PVC and a new pod will be created and should come up fine.

**Comment by embik** [comment]
This bug was introduced in #9600.
