### ISSUE TITLE
kubermatic-seed-controller-manager crashes with concurrent map writes

### ISSUE THREAD

**Issue by embik** [kubermatic/kubermatic#11840]
### What happened?

kubermatic-seed-controller-manager is occasionally (at 37 restarts since the upgrade yesterday) crashing in our 2.22 QA environment. It seems to be related to kubevirt client code and mirrors what is happening in kubermatic-api (https://github.com/kubermatic/dashboard/issues/5660), also related to kubevirt code.

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 2413 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc00028d880, {{0x4316a19, 0xb}, {0x43050aa, 0x2}, {0x3606da8, 0x16}}, {0x4a31f78?, 0xc001c50100})
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme.go:175 +0x2f7
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc00028d880, {{0x4316a19?, 0x0?}, {0x43050aa?, 0x40dc07?}}, {0xc002b4fef0?, 0xc, 0x7fcea6003ad0?})
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme.go:149 +0x237
kubevirt.io/api/core/v1.AddKnownTypesGenerator.func1(0xc005508be0?)
	kubevirt.io/api@v0.58.0/core/v1/register.go:92 +0x34b
k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x4a41960?, 0xc005508be0?)
	k8s.io/apimachinery@v0.26.1/pkg/runtime/scheme_builder.go:29 +0x5b
k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt.newClient({0xc0018cc000, 0x1626}, {{0x0, {0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0, 0x0}, ...})
	k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt/client.go:73 +0x1c2
k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt.NewClient(...)
	k8c.io/kubermatic/v2/pkg/provider/cloud/kubevirt/client.go:90
k8c.io/kubermatic/v2/pkg/resources/csi/kubevirt.InfraAccessSecretReconciler.func1.1(0xc00322c280)
	k8c.io/kubermatic/v2/pkg/resources/csi/kubevirt/secret.go:52 +0x2ac
k8c.io/reconciler/pkg/reconciling.SecretObjectWrapper.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/zz_generated_reconcile.go:121 +0x3f
k8c.io/reconciler/pkg/reconciling.CreateWithNamespace.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:46 +0x3d
k8c.io/reconciler/pkg/reconciling.CreateWithName.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:57 +0x3d
k8c.io/reconciler/pkg/reconciling.CreateWithNamespace.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:46 +0x3d
k8c.io/reconciler/pkg/reconciling.CreateWithName.func1({0x4a75f70?, 0xc00322c280?})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:57 +0x3d
k8c.io/reconciler/pkg/reconciling.EnsureNamedObject({0x4a44108, 0xc0027b8900}, {{0xc003107008?, 0x0?}, {0x433c986?, 0x0?}}, 0x0?, {0x4a5baa8, 0xc000931140}, {0x4a75f70, ...}, ...)
	k8c.io/reconciler@v0.3.1/pkg/reconciling/ensure.go:122 +0x602
k8c.io/reconciler/pkg/reconciling.ReconcileSecrets({0x4a44108, 0xc0027b8900}, {0xc004f1db00, 0x1f, 0xc004cd5800?}, {0xc003107008, 0x12}, {0x4a5baa8, 0xc000931140}, {0x0, ...})
	k8c.io/reconciler@v0.3.1/pkg/reconciling/zz_generated_reconcile.go:139 +0x186
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).ensureSecrets(0xc000031a40, {0x4a44108, 0xc0027b8900}, 0xc004cd5800, 0xc004cd5800?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/resources.go:506 +0x96
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).ensureResourcesAreDeployed(0xc000031a40, {0x4a44108, 0xc0027b8900}, 0xc004cd5800, 0x1?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/resources.go:105 +0x31a
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).reconcileCluster(0xc000031a40?, {0x4a44108, 0xc0027b8900}, 0xc004cd5800, 0x6d3ea40?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/pending.go:51 +0x19b
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).reconcile(0xc000031a40, {0x4a44108?, 0xc0027b8900}, 0xc000031a40?, 0xc004cd5800)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:310 +0x385
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).Reconcile.func1()
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:268 +0x9a
k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1/helper.ClusterReconcileWrapper({0x4a44108, 0xc0027b8900}, {0x4a5baa8, 0xc000931140}, {0x7ffccdd2929c, 0x0}, 0xc004cd5800, {{0x49ffdf0, 0x1c}, {0x4a34240, ...}, ...}, ...)
	k8c.io/kubermatic/v2/pkg/apis/kubermatic/v1/helper/helper.go:86 +0xe2
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes.(*Reconciler).Reconcile(0xc000031a40, {0x4a44108, 0xc0027b8900}, {{{0x0?, 0x10?}, {0xc003815656?, 0x40dc07?}}})
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go:252 +0x2f8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4a44108?, {0x4a44108?, 0xc0027b8900?}, {{{0x0?, 0x38f9ea0?}, {0xc003815656?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000c3cbe0, {0x4a44060, 0xc000947fc0}, {0x3d30ea0?, 0xc0030a9400?})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000c3cbe0, {0x4a44060, 0xc000947fc0})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:231 +0x333
```

### Expected behavior

kubermatic-seed-controller-manager shouldn't be crashing.

### How to reproduce the issue?

Unclear, but looks like interacting with / creating KubeVirt clusters can trigger the code in question.

### How is your environment configured?

- KKP version: v2.22.0-alpha.0
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

N/A

### What operating system are you running in your user cluster?

N/A

**Comment by hdurand0710** [comment]
There is also another crash reason:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x34eff3b]

goroutine 1474 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x3b2ee20, 0x6d06700})
	runtime/panic.go:884 +0x212
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/mla.(*userGrafanaController).ensureGrafanaUser(0xc000647cc0, {0x4a44108, 0xc0052330e0}, 0xc000c73520, 0x4a74df0?)
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/mla/user_grafana_controller.go:342 +0xc5b
k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/mla.(*userGrafanaReconciler).Reconcile(0xc0002bb220, {0x4a44108, 0xc0052330e0}, {{{0x0?, 0x10?}, {0xc0034b9fc0?, 0x40dc07?}}})
	k8c.io/kubermatic/v2/pkg/controller/seed-controller-manager/mla/user_grafana_controller.go:192 +0x409
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4a44108?, {0x4a44108?, 0xc0052330e0?}, {{{0x0?, 0x38f9ea0?}, {0xc0034b9fc0?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002bb360, {0x4a44060, 0xc0007ad780}, {0x3d30ea0?, 0xc003d9d5a0?})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002bb360, {0x4a44060, 0xc0007ad780})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:231 +0x333
```

**Comment by embik** [comment]
Great catch. We should make sure we fix both of them.

**Comment by mfranczy** [comment]
but the Grafana error should be fixed by somebody from sig applications.

**Comment by rastislavs** [comment]
> but the Grafana error should be fixed by somebody from sig applications.

Fixed in https://github.com/kubermatic/kubermatic/pull/11843
