### ISSUE TITLE
failed to patch cluster: unable to find api field in struct Unstructured for the json field "metadata"

### ISSUE THREAD

**Issue by thz** [kubermatic/kubermatic#1294]
### Context

The cluster controller has an `updateCluster(orig, modified)` function which uses `jsonmergepatch.CreateThreeWayJSONMergePatch()` to create patchData for `cc.kubermaticClient.KubermaticV1().Clusters().Patch()`.

### Issue

With current master `Clusters().Patch()` errors with:
```
failed to patch cluster: unable to find api field in struct Unstructured for the json field "metadata"
```
This seems to happen when sending the PATCH towards apiserver at GKE.  `/logs/kube-apiserver.log` contains a backtrace for that the PATCH request which returns status=500.
```
E0615 07:06:51.310053       1 status.go:64] apiserver received an error that is not an metav1.Status: unable to find api field in struct Unstructured for the json field "address"
I0615 07:06:51.310277       1 wrap.go:42] PATCH /apis/kubermatic.k8s.io/v1/clusters/9f2rfwkz2m: (13.905559ms) 500

```
(Full backtrace follows in comment.)

### Details

I have isolated one such case which is a simple modification triggered by pausing the cluster (`kubectl edit cluster ...`). The 3 parts of the 3-way merge seem valid:

```
original=
{"metadata":{"name":"9f2rfwkz2m","selfLink":"/apis/kubermatic.k8s.io/v1/clusters/9f2rfwkz2m","uid":"a8f88510-706a-11e8-a141-42010a9c00c6","resourceVersion":"94070687","generation":1,"creationTimestamp":"2018-06-15T07:06:43Z","labels":{"user":"xxx","worker-name":"thz-vmface"},"finalizers":["kubermatic.io/cleanup-backups","kubermatic.io/cleanup-aws-security-group"]},"spec":{"cloud":{"dc":"aws-eu-central-1a","aws":{"accessKeyId":"xxx","secretAccessKey":"xxx","vpcId":"vpc-819f62e9","subnetId":"subnet-2bff4f43","roleName":"","routeTableId":"","instanceProfileName":"","securityGroupID":"sg-c145abad","availabilityZone":"eu-central-1a"}},"clusterNetwork":{"services":{"cidrBlocks":null},"pods":{"cidrBlocks":null},"dnsDomain":""},"version":"1.10.3","masterVersion":"1.10.3","humanReadableName":"thz-01","workerName":"thz-vmface","pause":false},"address":{"url":"","externalName":"","kubeletToken":"","adminToken":"","ip":""},"status":{"lastUpdated":null,"phase":"Launching","lastDeployedMasterVersion":"","rootCA":{"key":"","cert":""},"apiserverCert":{"key":"","cert":""},"kubeletCert":{"key":"","cert":""},"apiserverSshKey":{"privateKey":"","publicKey":""},"serviceAccountKey":"","namespaceName":"cluster-9f2rfwkz2m","userName":"Tobias Hintze","userEmail":"xxx@loodse.com","errorReason":"ReconcileError","errorMessage":"failed to create instance profile: failed to create role: EntityAlreadyExists: Role with name kubermatic-role-9f2rfwkz2m already exists.\n\tstatus code: 409, request id: b2100abe-706a-11e8-85d6-c769e2c0a160"}}

currentData=
{"metadata":{"name":"9f2rfwkz2m","selfLink":"/apis/kubermatic.k8s.io/v1/clusters/9f2rfwkz2m","uid":"a8f88510-706a-11e8-a141-42010a9c00c6","resourceVersion":"94070688","generation":1,"creationTimestamp":"2018-06-15T07:06:43Z","labels":{"user":"xxx","worker-name":"thz-vmface"},"finalizers":["kubermatic.io/cleanup-backups","kubermatic.io/cleanup-aws-security-group"]},"spec":{"cloud":{"dc":"aws-eu-central-1a","aws":{"accessKeyId":"xxx","secretAccessKey":"xxx","vpcId":"vpc-819f62e9","subnetId":"subnet-2bff4f43","roleName":"","routeTableId":"","instanceProfileName":"","securityGroupID":"sg-c145abad","availabilityZone":"eu-central-1a"}},"clusterNetwork":{"services":{"cidrBlocks":null},"pods":{"cidrBlocks":null},"dnsDomain":""},"version":"1.10.3","masterVersion":"1.10.3","humanReadableName":"thz-01","workerName":"thz-vmface","pause":true},"address":{"url":"","externalName":"","kubeletToken":"","adminToken":"","ip":""},"status":{"lastUpdated":null,"phase":"Launching","lastDeployedMasterVersion":"","rootCA":{"key":"","cert":""},"apiserverCert":{"key":"","cert":""},"kubeletCert":{"key":"","cert":""},"apiserverSshKey":{"privateKey":"","publicKey":""},"serviceAccountKey":"","namespaceName":"cluster-9f2rfwkz2m","userName":"Tobias Hintze","userEmail":"xxx@loodse.com","errorReason":"ReconcileError","errorMessage":"failed to create instance profile: failed to create role: EntityAlreadyExists: Role with name kubermatic-role-9f2rfwkz2m already exists.\n\tstatus code: 409, request id: b2100abe-706a-11e8-85d6-c769e2c0a160"}}

modifiedData=
{"metadata":{"name":"9f2rfwkz2m","selfLink":"/apis/kubermatic.k8s.io/v1/clusters/9f2rfwkz2m","uid":"a8f88510-706a-11e8-a141-42010a9c00c6","resourceVersion":"94070687","generation":1,"creationTimestamp":"2018-06-15T07:06:43Z","labels":{"user":"xxx","worker-name":"thz-vmface"},"finalizers":["kubermatic.io/cleanup-backups","kubermatic.io/cleanup-aws-security-group"]},"spec":{"cloud":{"dc":"aws-eu-central-1a","aws":{"accessKeyId":"xxx","secretAccessKey":"xxx","vpcId":"vpc-819f62e9","subnetId":"subnet-2bff4f43","roleName":"","routeTableId":"","instanceProfileName":"","securityGroupID":"sg-c145abad","availabilityZone":"eu-central-1a"}},"clusterNetwork":{"services":{"cidrBlocks":null},"pods":{"cidrBlocks":null},"dnsDomain":""},"version":"1.10.3","masterVersion":"1.10.3","humanReadableName":"thz-01","workerName":"thz-vmface","pause":false},"address":{"url":"","externalName":"","kubeletToken":"","adminToken":"","ip":""},"status":{"lastUpdated":null,"phase":"Launching","lastDeployedMasterVersion":"","rootCA":{"key":"","cert":""},"apiserverCert":{"key":"","cert":""},"kubeletCert":{"key":"","cert":""},"apiserverSshKey":{"privateKey":"","publicKey":""},"serviceAccountKey":"","namespaceName":"cluster-9f2rfwkz2m","userName":"Tobias Hintze","userEmail":"xxx@loodse.com","errorReason":"ReconcileError","errorMessage":"failed to create instance profile: failed to create role: EntityAlreadyExists: Role with name kubermatic-role-9f2rfwkz2m already exists.\n\tstatus code: 409, request id: b238c7fd-706a-11e8-85d6-c769e2c0a160"}}
```

The resultant patchData:
```
patchData=
{"metadata":{"resourceVersion":"94070687"},"spec":{"pause":false},"status":{"errorMessage":"failed to create instance profile: failed to create role: EntityAlreadyExists: Role with name kubermatic-role-9f2rfwkz2m already exists.\n\tstatus code: 409, request id: b238c7fd-706a-11e8-85d6-c769e2c0a160"}}
```

Also it seems to me that the error message has not much to do with the actual patching data but is more about how CRD should be patched in general. I am not 100% sure here but found related issues:

https://github.com/kubernetes/kubernetes/issues/52772

just that we are already doing it like suggested in there as a fix.

**Comment by thz** [comment]
```
E0615 07:06:51.310053       1 status.go:64] apiserver received an error that is not an metav1.Status: unable to find api field in struct Unstructured for the json field "address"
I0615 07:06:51.310277       1 wrap.go:42] PATCH /apis/kubermatic.k8s.io/v1/clusters/9f2rfwkz2m: (13.905559ms) 500
goroutine 315045613 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4343edab0, 0x1f4)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4343edab0, 0x1f4)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc424ad9680, 0x1f4)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:188 +0xac
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc42efade50, 0x1f4)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:220 +0x63
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc438deec90, 0x1f4)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:281 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x3e59d3d, 0x10, 0x7ff2c75709a0, 0xc43347a900, 0x99f0440, 0xc435a046d8, 0xc4331abf00, 0x1f4, 0x99d7240, 0xc433d20ab0)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:95 +0x8d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7ff2c2c21c48, 0xc438deec60, 0x99f2d00, 0xc4405bdd40, 0xc43f955ce0, 0x11, 0xc4263315e8, 0x2, 0x99f0440, 0xc435a046d8, ...)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:123 +0x32b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7ff2c2c21c48, 0xc438deec60, 0x99ba040, 0xc432355dd0, 0x99f2d00, 0xc4405bdd40, 0xc43f955ce0, 0x11, 0xc4263315e8, 0x2, ...)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:142 +0x163
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc4398d3a40, 0x99ba040, 0xc432355dd0, 0x99f0440, 0xc435a046d8, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:67 +0x10c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.PatchResource.func1(0x99f0440, 0xc435a046d8, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:130 +0x1205
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentHandlerFunc.func1(0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:221 +0x1e0
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc4202ec700, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:219 +0x52a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc4231149c0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4203c8d90, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3e733ed, 0x17, 0xc420e66360, 0xc4203c8d90, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4209c7aa0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42495b840, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:254 +0x407
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc420585dc0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3e54408, 0xe, 0xc420bac090, 0xc420585dc0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4209a6a20, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc44892f200, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:93 +0x18a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc432576100, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4228ff260, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3e571d8, 0xf, 0xc425c1cea0, 0xc4228ff260, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4261137e0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:52 +0x37d
net/http.HandlerFunc.ServeHTTP(0xc422a716d0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:165 +0x42a
net/http.HandlerFunc.ServeHTTP(0xc422f41fc0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x203a
net/http.HandlerFunc.ServeHTTP(0xc422a717c0, 0x99f0340, 0xc435a046d0, 0xc4331abf00)
    /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7ff2c27fe520, 0xc435a046c8, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:105 +0x501
net/http.HandlerFunc.ServeHTTP(0xc422a718b0, 0x7ff2c27fe520, 0xc435a046c8, 0xc4331abf00)
    /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7ff2c27fe520, 0xc435a046c8, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:78 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc422a719f0, 0x7ff2c27fe520, 0xc435a046c8, 0xc4331abf00)
    /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7ff2c27fe520, 0xc435a046c8, 0xc4331abf00)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc426113800, 0x7ff2c27fe520, 0xc435a046c8, 0xc4331abf00)
    /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4261138a0, 0x99f4d80, 0xc435a046c8, 0xc4331abf00, 0xc44c1c6480)
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
    /workspace/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:92 +0x1ab
```

**Comment by thz** [comment]
https://github.com/kubernetes/helm/issues/3382

**Comment by thz** [comment]
#1324

**Comment by sttts** [comment]
@thz unfortunatelly the backtrace does not help much. We need one from the location where `unable to find api field in struct Unstructured for the json field "address"` is actually created.

**Comment by thz** [comment]
Need to reproduce that again but with current master we workarounded this by no longer patching (in favor of updating). My guess was that it was related to the resourceVersion attribute.

**Comment by sttts** [comment]
> My guess was that it was related to the resourceVersion attribute.

I tried that in an artificial test and didn't see the symptom you have above.
