### ISSUE TITLE
VMware Cloud Director CSI driver is broken

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubermatic#13021]
Post https://github.com/kubermatic/kubermatic/pull/12936, it seems that the CSI driver for VMware Cloud Director is broken.

The pod for  CSI controller is crashing with the following logs:

```
E0201 09:21:01.850229       1 disks.go:888] error occurred when getting defined entity [ip26kxrp44]; skipping upgrade of CSI status section: [{"minorErrorCode":"ACCESS_TO_RESOURCE_IS_FORBIDDEN","message":"[ 34bf6503-e7f1-4293-8b3e-196e498fda7a ] This operation is denied.","stackTrace":null}]
E0201 09:21:02.141112       1 driver.go:148] unable to add error [RdeUpgradeError] into [CSI.Errors] in RDE [ip26kxrp44], failed to get RDE [ip26kxrp44] when adding error to the errorSet of [csi] ; expected http response [200], obtained [403]: resp: ["{\"minorErrorCode\":\"ACCESS_TO_RESOURCE_IS_FORBIDDEN\",\"message\":\"[ e7fb5c36-8af7-4309-a253-738efcec595a ] This operation is denied.\",\"stackTrace\":null}"]: [403 Forbidden]
panic: error while setting up driver: [CSI section upgrade failed when CAPVCD RDE is present, [error when getting defined entity [ip26kxrp44] from VCD: [403 Forbidden]; skipping upgrade of CSI status section to Version [1.5.0]]]

goroutine 1 [running]:
main.runCommand()
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/cmd/csi/main.go:153 +0x4d6
main.main.func2(0xc0002a0000?, {0x123916f?, 0x4?, 0x4?})
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/cmd/csi/main.go:67 +0x17
github.com/spf13/cobra.(*Command).execute(0xc0002a0000, {0xc0000340b0, 0x4, 0x4})
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/vendor/github.com/spf13/cobra/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002a0000)
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/vendor/github.com/spf13/cobra/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/build/mts/release/bora-22973363/cayman_cloud-director-named-disk-csi-driver/cloud-director-named-disk-csi-driver/src/cmd/csi/main.go:87 +0x228
```

**Comment by ahmedwaleedmalik** [comment]
This also blocks https://github.com/kubermatic/kubermatic/pull/13020
