### ISSUE TITLE
Upgrade to Go 1.13

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#4415]
### User Story
We want to use the most recent Go version for building and testing Kubermatic.

#### Go-Swagger
With the current set of dependencies, running `make verify` breaks:

```
$ docker run --rm -it -v $(realpath .):/go/src/github.com/kubermatic/kubermatic -e GO111MODULE=off -w /go/src/github.com/kubermatic/kubermatic golang:1.13.1 make -C api verify
make: Entering directory '/go/src/github.com/kubermatic/kubermatic/api'
.......
./hack/verify-swagger.sh
panic: Invalid schema provided to SchemaValidator: object has no key "default"

goroutine 1 [running]:
github.com/kubermatic/kubermatic/api/vendor/github.com/go-openapi/validate.NewSchemaValidator(0xc000b5ed80, 0xc4e5c0, 0xc000b5ed80, 0x0, 0x0, 0xde0560, 0xc0004420c0, 0xc00093fb90)
        /go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/go-openapi/validate/schema.go:71 +0xf83
github.com/kubermatic/kubermatic/api/vendor/github.com/go-openapi/validate.(*SpecValidator).Validate(0xc000ce4940, 0xc080c0, 0xc000af1770, 0xc000d02fd0, 0xc0000ba000)
        /go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/go-openapi/validate/spec.go:92 +0x208
github.com/kubermatic/kubermatic/api/vendor/github.com/go-swagger/go-swagger/cmd/swagger/commands.(*ValidateSpec).Execute(0xc00038b858, 0xc0003d6200, 0x1, 0x2, 0xc00038b858, 0x1)
        /go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/go-swagger/go-swagger/cmd/swagger/commands/validate.go:60 +0x14e
github.com/kubermatic/kubermatic/api/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0004c7200, 0xc0000b0010, 0x2, 0x2, 0x0, 0xcabd5c, 0x2a, 0xb2e880, 0xc00027fe30)
        /go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x8dc
github.com/kubermatic/kubermatic/api/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/jessevdk/go-flags/parser.go:186
main.main()
        /go/src/github.com/kubermatic/kubermatic/api/vendor/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:140 +0xb60
make: *** [Makefile:110: verify] Error 2
make: Leaving directory '/go/src/github.com/kubermatic/kubermatic/api'
```

### Acceptance criteria
* [ ] Go < 1.13 is not used anywhere in our pipeline.

**Comment by maciaszczykm** [comment]
Seems to be done:

```
~/Workspace/kubermatic on  master ➜ go version                               
go version go1.15 darwin/amd64

~/Workspace/kubermatic on  master ➜ ./hack/verify-swagger.sh                 
2020/08/19 13:10:48 
The swagger spec at "swagger.json" is valid against swagger specification 2.0
2020/08/19 13:10:48 
The swagger spec at "swagger.json" showed up some valid but possibly unwanted constructs.
2020/08/19 13:10:48 See warnings below:
2020/08/19 13:10:48 - WARNING: definition "#/definitions/PublicCloudSpec" is not used anywhere
2020/08/19 13:10:48 - WARNING: definition "#/definitions/Time" is not used anywhere
2020/08/19 13:10:48 - WARNING: definition "#/definitions/ResourceType" is not used anywhere
2020/08/19 13:10:48 - WARNING: definition "#/definitions/ObjectMeta" is not used anywhere

```
