### ISSUE TITLE
Panic flag redefined: log_dir after upgrade to k8s to 1.3.5

### ISSUE THREAD

**Issue by scheeles** [kubermatic/kubermatic#63]
After upgrading k8s dependencies to 1.3.5 I go the following dump when I try to run api-server

```
/private/var/folders/2s/dnrtgx8j4wz4w50pj31d57fc0000gn/T/API-Servergo flag redefined: log_dir
panic: /private/var/folders/2s/dnrtgx8j4wz4w50pj31d57fc0000gn/T/API-Servergo flag redefined: log_dir

goroutine 1 [running]:
panic(0x59140a0, 0xc82010e190)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
flag.(*FlagSet).Var(0xc820072060, 0x8f54708, 0xc82010e140, 0x60404e8, 0x7, 0x61e30a0, 0x2f)
    /usr/local/opt/go/libexec/src/flag/flag.go:776 +0x454
flag.(*FlagSet).StringVar(0xc820072060, 0xc82010e140, 0x60404e8, 0x7, 0x0, 0x0, 0x61e30a0, 0x2f)
    /usr/local/opt/go/libexec/src/flag/flag.go:679 +0xc7
flag.(*FlagSet).String(0xc820072060, 0x60404e8, 0x7, 0x0, 0x0, 0x61e30a0, 0x2f, 0xc82010e130)
    /usr/local/opt/go/libexec/src/flag/flag.go:692 +0x83
flag.String(0x60404e8, 0x7, 0x0, 0x0, 0x61e30a0, 0x2f, 0x463c1e2)
    /usr/local/opt/go/libexec/src/flag/flag.go:699 +0x5f
github.com/kubermatic/api/vendor/github.com/golang/glog.init()
    /Users/Sebastian/git/kubermatic/src/github.com/kubermatic/api/vendor/github.com/golang/glog/glog_file.go:41 +0x13c
github.com/kubermatic/api/handler.init()
    /Users/Sebastian/git/kubermatic/src/github.com/kubermatic/api/handler/user.go:60 +0x6c
main.init()
    /Users/Sebastian/git/kubermatic/src/github.com/kubermatic/api/cmd/kubermatic-api/main.go:56 +0x5e

Process finished with exit code 2

```

this is the line which create the trouble https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/golang/glog/glog_file.go#L41

**Comment by s-urbaniak** [comment]
apparently `log_dir` is being initalized twice as a flag.

can you `ag log_dir` (https://github.com/ggreer/the_silver_searcher) in the top of your source directory to check if there are multiple hits?

I guess when upgrading to k8s 1.3.5 multiple copies of glog happened to sneak in.

**Comment by scheeles** [comment]
As far as I can see, the line is only execute once. I check it with debug.

Here is the output :

```
 ~/git/kubermatic/src: ag "var logDir = flag.String"
github.com/coreos/etcd/cmd/vendor/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

github.com/kubermatic/api/vendor/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

github.com/kubermatic/api/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

github.com/mesos/mesos-go/examples/Godeps/_workspace/src/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")

k8s.io/kubernetes/vendor/github.com/golang/glog/glog_file.go
41:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")
```

**Comment by scheeles** [comment]
Issue was due to the fact Godep don't handle all dependencies correctly.

See also #66
