### ISSUE TITLE
Update etcd to v3.5.1

### ISSUE THREAD

**Issue by jplgec** [kubermatic/kubermatic#8558]
**User Story**

If a broken etcd member in a customer cluster is removed (i.e. as described here: https://docs.kubermatic.com/kubermatic/v2.18/cheat_sheets/etcd/replace_a_member/), the recovery fails with the current hardcoded etcd version v3.5.0: 

```
{"level":"warn","ts":"2021-12-29T22:03:25.166Z","caller":"membership/cluster.go:427","msg":"skipped removing already removed member","cluster-id":"6719648a80b0d22f","local-member-id":"c2271aecf5aa3549","removed-remote-peer-id":"1f4e20abfd0dc3a1"}
{"level":"panic","ts":"2021-12-29T22:03:25.166Z","caller":"rafthttp/transport.go:346","msg":"unexpected removal of unknown remote peer","remote-peer-id":"1f4e20abfd0dc3a1","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/api/rafthttp/transport.go:346\ngo.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/api/rafthttp/transport.go:329\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:2301\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:2133\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:1357\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:1179\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:1111\ngo.etcd.io/etcd/pkg/v3/schedule.(*fifo).run\n\t/tmp/etcd-release-3.5.0/etcd/release/etcd/pkg/schedule/schedule.go:157"}
panic: unexpected removal of unknown remote peer

goroutine 156 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc051f51a40, 0xc06765a480, 0x1, 0x1)
	/home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x58d
go.uber.org/zap.(*Logger).Panic(0xc000094a50, 0x122d9ab, 0x29, 0xc06765a480, 0x1, 0x1)
	/home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:227 +0x85
go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer(0xc000345c00, 0x1f4e20abfd0dc3a1)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/api/rafthttp/transport.go:346 +0x58c
go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer(0xc000345c00, 0x1f4e20abfd0dc3a1)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/api/rafthttp/transport.go:329 +0x7d
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange(0xc000138700, 0x1, 0x1f4e20abfd0dc3a1, 0x0, 0x0, 0x0, 0x54d77e07ff4234d6, 0xc00058a500, 0x0, 0x0, ...)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:2301 +0x872
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply(0xc000138700, 0xc070dd8ef0, 0x49, 0x1105, 0xc00058a500, 0xc077f479d8, 0xc077f47990, 0xc705fd)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:2133 +0x59a
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries(0xc000138700, 0xc00058a500, 0xc077f50a50)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:1357 +0xe5
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll(0xc000138700, 0xc00058a500, 0xc077f50a50)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:1179 +0x88
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8(0x1399c10, 0xc071213a80)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/server/etcdserver/server.go:1111 +0x3c
go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run(0xc0000994a0)
	/tmp/etcd-release-3.5.0/etcd/release/etcd/pkg/schedule/schedule.go:157 +0xf3
created by go.etcd.io/etcd/pkg/v3/schedule.NewFIFOScheduler
	/tmp/etcd-release-3.5.0/etcd/release/etcd/pkg/schedule/schedule.go:70 +0x13b
```

If the cluster is paused and the etcd StatefulSet is updated to etcd version 3.5.1, etcd comes up and everything is working fine.

**Acceptance criteria**

* the hardcoded etcd version for customer clusters is changed to (at least) v3.5.1

**Comment by embik** [comment]
I quickly tried to replicate this issue but couldn't (following the restore procedure with an etcd cluster on 3.5.0 was working just fine), but it sounds a lot like https://github.com/etcd-io/etcd/issues/13119. We should look into doing the upgrade.

@jplgec Just wondering, have you been able to reproduce this problem on fresh clusters (deployed initially with Kubernetes 1.22, which gets 3.5.0 as etcd version) or is this only for clusters upgraded from previous versions?

**Comment by jplgec** [comment]
to answer your question: couldn't reproduce it on a freshly created 1.22 cluster with etcd 3.5.0 running

**Comment by embik** [comment]
Understood, thanks. I will test with that in mind again. This probably needs a backport as well.
